### ISSUE TITLE
Investigate LOBPCG convergence in silicon supercells

### ISSUE THREAD

**Issue by antoine-levitt** [mfherbst/DFTK.jl#41]
On https://github.com/mfherbst/DFTK.jl/pull/40 with `supercell = [3,1,1]` and `display_progress=true` in the eigensolver, the eigensolver fails to converge. Not sure if there are not enough extra bands or if we're doing something wrong. Need to investigate this to do David's thing. Also not sure what convergence criteria people typically take for the iterative eigensolver, but I'm pretty sure it's way less tight than what we do now.

@mfherbst I hope you don't mind, I'm kinda using the issue tracker as a TODO list...

**Comment by mfherbst** [comment]
No I don't. Will be fun more fun once we implement it :). I'm actually on David's thing right now playing with it and ran into the same issue :smile:.

**Comment by antoine-levitt** [comment]
Fixed in #42, was definitely me being stupid
