### ISSUE TITLE
PlaneWaveModel and kpoints names

### ISSUE THREAD

**Issue by antoine-levitt** [mfherbst/DFTK.jl#49]
- We call objects of type PlaneWaveModel `basis`, so let's just rename to `PlaneWaveBasis`? `PWBasis` for short?

- `kpoints` is sometimes used for coordinates, sometimes for `KPoint`, which confused me. Rename the first use to `kcoords`?

**Comment by mfherbst** [comment]
How about PWModel ... it is a model after al ... that's how we ended up with this name.

Re kpoints: Really ... that can only be leftovers in the tests or so, definitely not intentional

**Comment by antoine-levitt** [comment]
I think the fact we took to calling it basis is a strong indication it's best thought as a basis than a model. I get your point and I know that's what we settled on, but usually we don't think of discretizing a model as creating a model - it's just an approximation of the model. We could call it PWDiscretization but basis is simpler I think. 

RE kpoints, it's mostly in examples and in bz handling

**Comment by mfherbst** [comment]
Ok, let's go with `PWBasis` then.

That's all things I did not modify a lot during the last restructuring pass. I tried to make sure it's clear that `kcoords` is a plain vector and `kpt` or `kpoints` KPoint objects, but I might have missed something.
